apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-configmap
data:
  MONGO_URI: "mongodb+srv://Haolong:Long0703020@cluster0.ptogg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "5000"
  CLOUDINARY_CLOUD_NAME: "drksaby9a"