apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  CLOUDINARY_API_KEY: "NDI2NDYyNDMyMzM5ODQy"
  CLOUDINARY_API_SECRET: "a0wxZXgtVjk1VU1Ba2huY2lLSmdRX05TcHRn"
  JWT_SECRET: "K0hxdXVib3BMaHMxSElHbDBTUkw5QmFUcWJMNk9oVWVEYzl5MFNORk8wdz0="
