apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  CLOUDINARY_API_KEY: "NDI2NDYyNDMyMzM5ODQy"
  CLOUDINARY_API_SECRET: "a0wxZXgtVjk1VU1Ba2huY2lLSmdRX05TcHRn"
  JWT_SECRET: "K0hxdXVib3BMaHMxSElHbDBTUkw5QmFUcWJMNk9oVWVEYzl5MFNORk8wdz0="
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9IYW9sb25nOkxvbmcwNzAzMDIwQGNsdXN0ZXIwLnB0b2dnLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
